apps/budgets/urls.py
from django.urls import path
from . import views

app_name = 'budgets'

urlpatterns =[
    path('set-budget/', views.set_budget, name="set_budget"),
    path('get_budgets/', views.get_budgets, name="get_budgets"),
    path('delete_budget/', views.delete_budget, name="delete_budget"),
    path('smart-saver/', views.smart_saver, name="smart_saver"),
    path('smart-categorization/', views.smart_categorization, name='smart_categorization'),
    path('api/get-smart-analysis/', views.get_smart_analysis_data, name='get_smart_analysis_data'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('chatbot-api/', views.chatbot_api, name='chatbot_api'),
]

apps/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns =[
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('visualize/', views.visualize, name='visualize'),
]

apps/transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    path('add_transaction/', views.submit_transaction, name="add_transaction"),
    path('delete_transaction/', views.delete_transaction, name="delete_transaction"),
    path('transaction_history/', views.transaction_history, name="transaction_history"),
    path('get_transactions/', views.get_transactions_history, name="get_transactions"),
    path('add_category/', views.add_category, name="add_category"),
]

neural_budget/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')), # Core app URLs
    path('accounts/', include('apps.accounts.urls')), # Accounts app URLs
    path('transactions/', include('apps.transactions.urls')), # Transactions app URLs
    path('budgets/', include('apps.budgets.urls')), # Budgets app URLs
    path('reports/', include('apps.reports.urls')), # Reports app URLs
    path('ml_features/', include('apps.ml_features.urls')), # ML Features app URLs
    path('datagen/', include('apps.datagen.urls')), # datagen app URLs
    path('insights/', include('apps.insights.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reports/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from apps.common_utils.firebase_config import FIREBASE_API_KEY
from apps.common_utils.auth_utils import get_user_id, get_email, get_user_full_name
from apps.common_utils.firebase_service import get_user_profile
from apps.reports.services import get_dashboard_data, generate_visualizations_data

def dashboard_view(request):
    dashboard_data = get_dashboard_data(request)
    context = {
        "FIREBASE_API_KEY": FIREBASE_API_KEY,
        "total_expenses": dashboard_data['total_expenses'],
        "total_income":dashboard_data['total_income'],
        "savings": dashboard_data['savings'],
        "recent_transactions": dashboard_data['recent_transactions'],
    }
    return render(request, 'reports/dashboard.html', context)

@csrf_exempt
def visualize(request):
    email = get_email(request)
    user_id = get_user_id(request)
    
    visualizations = generate_visualizations_data(user_id)
    
    data = {'email':email,'visualizations':visualizations}

    # Render the visualize.html template with visualizations
    return render(request, "reports/visualize.html",data)

apps/reports/templates/reports/dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Dashboard | Neural Budget AI{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'reports/css/dashboard.css' %}"/>
{% endblock %}

{% block content %}
        <section class="dashboard">
          <div class="dashboard-left">
            <div class="dashboard-cards">
              <div class="card">
                <h3>Total Expenses</h3>
                <p id="totalExpenses">₹{{ total_expenses|floatformat:2 }}</p>
              </div>
              <div class="card">
                <h3>Total Income</h3>
                <p id="totalIncome">₹{{ total_income|floatformat:2 }}</p>
              </div>
              <div class="card">
                <h3>Savings</h3>
                <p id="savings">₹{{ savings|floatformat:2 }}</p>
              </div>
              
            </div>

            <div class="recent-transactions">
              <h3>Recent Transactions</h3>
              <ul id="transactionList">
                {% for transaction in recent_transactions %}
                <li>
                  <span class="txn-name">{{ transaction.name }}:</span>
                  <span class="txn-amount"
                    >₹{{ transaction.amount|floatformat:2 }}</span
                  >
                  <span class="txn-type">{{ transaction.type }}</span>
                </li>
                {% empty %}
                <li>No recent transactions</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </section>
{% endblock %}

{% block extra_js %}
<script type="module" src="{% static 'reports/js/dashboard.js' %}"></script>

{% endblock %}

apps/reports/templates/reports/visualize.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Neural Budget AI</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    
    <link rel="stylesheet" href="{% static 'reports/css/sidebar-new.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script type="module" src="{% static 'reports/js/dashboard.js' %}"></script>
    <script type="module" src="{% static 'accounts/js/signOut.js' %}"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'reports/css/sidebar-new.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script type="module" src="{% static 'reports/js/dashboard.js' %}"></script>
    <script type="module" src="{% static 'accounts/js/signOut.js' %}"></script>
    <script type="module" src="{% static 'core/js/darkmode.js' %}"></script>
    
</head>
<body>
      <div id="chatbot-component" data-api-url="{% url 'core:chatbot_api' %}">
      {% include 'core/chatbot.html' %}
  </div>
    <div class="container">
    
</head>
<body>
      <div id="chatbot-component" data-api-url="{% url 'core:chatbot_api' %}">
      {% include 'core/chatbot.html' %}
  </div>
    <div class="container">

        <!-- SIDEBAR SECTION -->

        <aside class="sidebar">
            <div class="logo">
                <img src="{% static 'core/img/logo.png' %}" href="{% url 'reports:dashboard' %}" alt="Neural Budget AI Logo" class="logo-img">
                <span class="logo-text">Neural Budget AI</span>
            </div>            
            <nav>
                <ul>
                    <li class="dropdown">
                        <button class="drop-btn"><i class="fas fa-receipt"></i>Expense Tracking
                            <i class="fas fa-angle-right dropdown-icon"></i>
                        </button>
                        <ul class="dropdown-content">
                            <li><a href="/dashboard"><i class="fas fa-tachometer-alt"></i> Overview</a></li>
                            <li><a href="{% url 'transactions:add_transaction' %}"><i class="fas fa-plus-circle"></i> Add Expense</a></li>
                            <li><a href="{% url 'transactions:income_tracker' %}"><i class="fas fa-eye"></i> View Expenses</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="drop-btn"><i class="fas fa-wallet"></i>Budgeting Tools
                            <i class="fas fa-angle-right dropdown-icon"></i>
                        </button>
                        <ul class="dropdown-content">
                            <li><a href="{% url 'budgets:set_budget' %}"><i class="fas fa-coins"></i>Set Budget</a></li>
                            <li><a href="#"><i class="fas fa-piggy-bank"></i> Savings Goals</a></li>
                            <li><a href="#"><i class="fas fa-chart-pie"></i> Spending Insights</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="drop-btn"><i class="fas fa-chart-line"></i>AI Insights
                            <i class="fas fa-angle-right dropdown-icon"></i>
                        </button>
                        <ul class="dropdown-content"> 
                            <li><a href="{% url 'reports:visualize' %}"><i class="fas fa-brain"></i> Predictive Analysis</a></li>
                            <li><a href="#"><i class="fas fa-layer-group"></i> Smart Categorization</a></li>
                            <li><a href="#"><i class="fas fa-chart-line"></i> Expense Forecasting</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="drop-btn"><i class="fas fa-cog"></i>Settings
                            <i class="fas fa-angle-right dropdown-icon"></i>
                        </button>
                        <ul class="dropdown-content">
                            <li><a href="#"><i class="fas fa-user"></i> Profile</a></li>
                            <li><a href="#" id="signOutLink"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                        </ul>
                    </li>
                
                </ul>
            </nav>
        </aside>

        <main class="content">
            
        <!-- TOPBAR SECTION -->

            <header class="topbar">
                <div class="greeting">
                    <h3>Hi, {{email}} <i class="fas fa-smile"></i></h3>
                </div>
                
                <div class="actions">
                    <label class="switch">
                        <input type="checkbox" id="darkModeToggle">
                        <span class="slider round"></span>
                    </label>
                </div>
            </header>
            
            <section class="dashboard">
                <div class="container">
                    <div class="visualization">
                        <img src="data:image/png;base64,{{ visualizations.income_over_time }}" alt="Income Over Time">
                    </div>
                    
                    <div class="visualization">
                        <img src="data:image/png;base64,{{ visualizations.spending_categories }}" alt="Spending Categories">
                    </div>
                </div>
            </section>
        </main>
    </div>

    </main>
    </div>
</body>
</html>